# Project information
site_name: "DockSTARTer"
site_description: "DockSTARTer helps you get started with home server apps running in Docker."
site_author: "GhostWriters"
site_url: "https://dockstarter.com"

# Repository
repo_name: "GhostWriters/DockSTARTer"
repo_url: "https://github.com/GhostWriters/DockSTARTer"
edit_uri: "https://github.com/GhostWriters/DockSTARTer.com/edit/master/docs/"

# Copyright
copyright: "Copyright &copy; 2020 GhostWriters"

# Configuration
theme:
  name: "material"
  language: "en"
  palette:
    primary: "blue grey"
    accent: "indigo"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo: "img/icon.png"
  favicon: "img/favicon.ico"

# Navigation
nav:
  - Home: "index.md"
  - "introduction.md"
  - Basics:
    - "basics/available-apps.md"
    - "basics/migration.md"
    - "basics/env-var-info.md"
    - "basics/faq.md"
    - "basics/port-conflicts.md"
  - Advanced:
    - "advanced/advanced-usage.md"
    - "advanced/backups.md"
    - "advanced/macvlan.md"
    - "advanced/overrides.md"
    - "advanced/domain-info.md"
    - "advanced/smb-mounting.md"
    - "advanced/technical-info.md"
    - "advanced/vpn-info.md"
    - "advanced/uninstall.md"
  - App Specifics:
    - "apps/airdcpp.md"
    - "apps/airsonic.md"
    - "apps/bazarr.md"
    - "apps/beets.md"
    - "apps/bitwarden.md"
    - "apps/booksonic.md"
    - "apps/bookstack.md"
    - "apps/calibreweb.md"
    - "apps/cloudcmd.md"
    - "apps/cloudflareddns.md"
    - "apps/couchpotato.md"
    - "apps/dasshio.md"
    - "apps/ddclient.md"
    - "apps/deluge.md"
    - "apps/delugevpn.md"
    - "apps/duckdns.md"
    - "apps/duplicati.md"
    - "apps/emby.md"
    - "apps/filebot.md"
    - "apps/freshrss.md"
    - "apps/glances.md"
    - "apps/grafana.md"
    - "apps/guacamole.md"
    - "apps/h5ai.md"
    - "apps/handbrake.md"
    - "apps/headphones.md"
    - "apps/heimdall.md"
    - "apps/homeassistant.md"
    - "apps/htpcmanager.md"
    - "apps/hydra2.md"
    - "apps/influxdb.md"
    - "apps/jackett.md"
    - "apps/jellyfin.md"
    - "apps/lazylibrarian.md"
    - "apps/letsencrypt.md"
    - "apps/lidarr.md"
    - "apps/logarr.md"
    - "apps/logitechmediaserver.md"
    - "apps/makemkv.md"
    - "apps/mariadb.md"
    - "apps/mcmyadmin2.md"
    - "apps/medusa.md"
    - "apps/monitorr.md"
    - "apps/muximux.md"
    - "apps/mylar.md"
    - "apps/netdata.md"
    - "apps/nextcloud.md"
    - "apps/nzbget.md"
    - "apps/nzbgetvpn.md"
    - "apps/ombi.md"
    - "apps/openvpnas.md"
    - "apps/organizr.md"
    - "apps/ouroboros.md"
    - "apps/phpmyadmin.md"
    - "apps/pihole.md"
    - "apps/plex.md"
    - "apps/plexrequests.md"
    - "apps/portainer.md"
    - "apps/portaineragent.md"
    - "apps/pyload.md"
    - "apps/qbittorrent.md"
    - "apps/qbittorrentvpn.md"
    - "apps/quasselcore.md"
    - "apps/quasselweb.md"
    - "apps/radarr.md"
    - "apps/resiliosync.md"
    - "apps/rtorrentvpn.md"
    - "apps/rutorrent.md"
    - "apps/sabnzbd.md"
    - "apps/sabnzbdvpn.md"
    - "apps/samba.md"
    - "apps/sickchill.md"
    - "apps/sickrage.md"
    - "apps/smokeping.md"
    - "apps/sonarr.md"
    - "apps/synclounge.md"
    - "apps/syncthing.md"
    - "apps/tautulli.md"
    - "apps/telegraf.md"
    - "apps/thelounge.md"
    - "apps/transmission.md"
    - "apps/transmissionvpn.md"
    - "apps/ttrss.md"
    - "apps/tvheadend.md"
    - "apps/ubooquity.md"
    - "apps/unifi.md"
    - "apps/unificontroller.md"
    - "apps/varken.md"
    - "apps/vsftpd.md"
    - "apps/watchtower.md"
    - "apps/znc.md"
