---
site_name: DockSTARTer
site_description: DockSTARTer helps you get started with home server apps running in Docker.
site_author: GhostWriters
site_url: https://dockstarter.com

repo_url: https://github.com/GhostWriters/DockSTARTer
repo_name: GhostWriters/DockSTARTer

copyright: Copyright &copy; 2020 GhostWriters

extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/discord
      link: https://dockstarter.com/discord
    - icon: fontawesome/brands/github-square
      link: https://github.com/GhostWriters/DockSTARTer

google_analytics:
  - UA-8908801-4
  - auto

markdown_extensions:
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - redirects:
      redirect_maps:
        advanced/overrides.md: https://dockstarter.com/overrides/introduction
        apps/hydra2.md: https://dockstarter.com/apps/nzbhydra2/
        apps/letsencrypt.md: https://dockstarter.com/apps/swag/
        apps/plexrequests.md: https://dockstarter.com/apps/ombi/
        apps/ttrss.md: https://dockstarter.com/apps/freshrss/
        apps/unifi.md: https://dockstarter.com/apps/unificontroller/
        discord.md: https://discord.gg/xR3cyUb

theme:
  name: material
  features:
    - navigation.instant
  language: en
  favicon: img/favicon.ico
  logo: img/icon.png
  palette:
    primary: blue grey
    accent: indigo
