name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    needs: ["Lint Code Base"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: mkdocs
        run: |
          docker run --rm -v ${PWD}/site:/site -v ${PWD}:/docs squidfunk/mkdocs-material build --verbose --clean --strict
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./site
          cname: dockstarter.com
